### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by lovesegfault** [zsh-users/zsh-history-substring-search#104]
It will make packaging this much easier :)

**Comment by guidovansteen** [comment]
The project uses tags, but I agree they were used in a very sloppy way:

```
/p/t/f/git> date -R
Sat, 26 Oct 2019 09:50:48 +0200
/p/t/f/git> git for-each-ref refs/tags | cut -d " " -f 2
commit	refs/tags/1.0.6
tag	refs/tags/1.0.7
tag	refs/tags/1.0.8
commit	refs/tags/1.0.9
tag	refs/tags/v0.0.1-1
tag	refs/tags/v0.0.1-2
tag	refs/tags/v1.0.0
tag	refs/tags/v1.0.1
tag	refs/tags/v1.0.2
tag	refs/tags/v1.0.3
tag	refs/tags/v1.0.4
tag	refs/tags/v1.0.5
commit	refs/tags/v1.0.9
```

Some tags were annotated, some were not, and some tags started with "v" and some didn't. 

Thanks for drawing my attention to this! Here are the current tags. 

```
/p/t/f/git> date -R
Sat, 26 Oct 2019 10:04:56 +0200
/p/t/f/git> git for-each-ref refs/tags | cut -d " " -f 2
tag	refs/tags/v0.0.1-1
tag	refs/tags/v0.0.1-2
tag	refs/tags/v1.0.0
tag	refs/tags/v1.0.1
tag	refs/tags/v1.0.2
tag	refs/tags/v1.0.3
tag	refs/tags/v1.0.4
tag	refs/tags/v1.0.5
tag	refs/tags/v1.0.6
tag	refs/tags/v1.0.7
tag	refs/tags/v1.0.8
tag	refs/tags/v1.0.9
```

**Comment by lovesegfault** [comment]
That's curious, why does GitHub not show these tags? Have they not been pushed?
cc. https://github.com/zsh-users/zsh-history-substring-search/tags

**Comment by guidovansteen** [comment]
https://github.com/zsh-users/zsh-history-substring-search/ and https://github.com/zsh-users/fizsh are two separate projects. 

What is now in https://github.com/zsh-users/zsh-history-substring-search/ was originally started as a part of fizsh. zsh-history-substring-search actually consists of just a few scripts. It was split off to let other people use it without having to install the whole fizsh package. I guess that is the reason why https://github.com/zsh-users/zsh-history-substring-search/ only has two release tags. 

P.S. Since zsh-history-substring-search was split off, I have every now and then updated fizsh with the latest version of zsh-history-substring-search. I have also included more recent versions of zsh-users/zsh-syntax-highlighting in updates of fizsh.

**Comment by guidovansteen** [comment]
All right, and all the time I had the impression that your issue applied to fizsh... I just realize now that you filed it under zsh-history-substring-search. 

The reason for the lack of tags is probably that the devs did not think of making releases when they pushed their commits. Moreover, I think you can just pick the latest (and thus greatest) for packaging.

**Comment by guidovansteen** [comment]
Here is the reason why the latest tag was created: https://github.com/zsh-users/zsh-history-substring-search/issues/71. I will add a current tag for you if you need one.

**Comment by lovesegfault** [comment]
@guidovansteen Haha, this explains why I was befuddled looking for the tags.

Thanks for the new tag!
