### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by whatyouhide** [zsh-users/zsh-history-substring-search#37]
I'm on OSX 10.9, zsh 5.0.5. I can't seem to get this plugin to work.

I'm not using any frameworks.

With my usual configuration, I'm loading the plugin with antigen at the end of my `zshrc`:

```
...
antigen bundle zsh-users/zsh-completions src
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
...
```

And binding Up and Down arrows right after as described in the readme:

``` bash
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```

I also tried with `zsh -l -f`, sourcing the plugin:

``` bash
source ~/.antigen/repos/...pluginrepo.../zsh-history-substring-search.zsh
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```

([my zsh configuration](https://github.com/whatyouhide/zsh-config) for reference)

Thanks!

**Comment by RGBD** [comment]
Same problem with Fedora 21.
Binding ^[[A and ^[[B works.
You may want to update README.md

**Comment by sunaku** [comment]
@RGBD done in c4a83561a12b898ff7145856d0e6ae50757e28ba, thanks! :+1:

**Comment by apjanke** [comment]
This isn't necessarily a platform-dependent problem per se; it depends on whether `zsh` has been customized to set the cursor keypad to application mode while ZLE is active. The current Oh My Zsh and some Linux distros do so; the default is to not. The terminfo entries for the arrow keys and home/end only apply to their behavior in application cursor mode, not default cursor mode. (See `man terminfo`.) Those platforms or systems where you're seeing the need to fall back to hardcoded values instead of terminfo entries are those where they have the default `zsh` behavior of leaving the terminal in normal cursor mode while ZLE is active.

The behavior may also vary depending on what terminal and `$TERM` value you are using.

**Comment by z0rc** [comment]
@apjanke can you point to where OMZ sets mentioned ZLE customization? I don't use OMZ, but want to replicate similar behavior in my dotfiles.

**Comment by apjanke** [comment]
Sure. It's done by using `echoti smkx`/`rmkx` in `zle-line-init` and `zle-line-finish`. This is set up [in `lib/key-bindings.zsh`](https://github.com/robbyrussell/oh-my-zsh/blob/534bf2c608cad62ef96adfea94f7673a5c2e5c7a/lib/key-bindings.zsh#L5-L16) in the core OMZ code. You'll also need to do a `zmodload zsh/terminfo` first to make `$terminfo` available.

```
if (( ${+terminfo[smkx]} )) && (( ${+terminfo[rmkx]} )); then
  function zle-line-init() {
    echoti smkx
  }
  function zle-line-finish() {
    echoti rmkx
  }
  zle -N zle-line-init
  zle -N zle-line-finish
fi
```

My personal thinking is coming around to the idea that `zsh` extensions and "plugins" that bind cursor keys (up/down/left/right/home/end) should bind both the `$terminfo[kc*]` sequence and the corresponding hardcoded xterm normal-mode cursor sequence (`^[[A`, `^[[B`, `^[[C`, `^[[D`, `^[[H`, `^[[F`), so they work regardless of whether the user's `zsh` is configured to use application keypad mode while editing the command line. I haven't tested this much though, so I don't know if there are gotchas in practice.

**Comment by z0rc** [comment]
Thanks for detailed explanation, got it working for me.
