### ISSUE TITLE
oh-my-zsh is not the only ZSH framework that uses plugin.zsh files

### ISSUE THREAD

**Issue by unixorn** [zsh-users/zsh-history-substring-search#48]
Many other ZSH frameworks like [zgen](https://github.com/tarjoilija/zgen) and [Antigen](https://github.com/zsh-users/antigen) use .plugin.zsh files for compatibility with oh-my-zsh.

[2f8a5f8](https://github.com/zsh-users/zsh-history-substring-search/commit/2f8a5f8fe33d2f6165ac23336ed074296d65dec9) removes functionality for some non-oh-my-zsh-frameworks.

**Comment by sunaku** [comment]
Couldn't we update those other frameworks to reinstate whatever subset of the removed configuration they use on their end? Because those `$CASE_SENSITIVE` and `$DISABLE_COLOR` flags aren't part of ZSH itself.

**Comment by sunaku** [comment]
:exclamation: Ping @unixorn. Is this still an issue?  Have those frameworks reconfigured this plugin since?  Thanks.

**Comment by Tarrasch** [comment]
@sunaku You can easily fix this issue by having a commit like this one: https://github.com/Tarrasch/zsh-history-substring-search/commit/f20ed56e2070bfbef9f7968d2619f5ea4a09e256, I already did it in https://github.com/sindresorhus/pure/pull/75 and it was appreciated there. :)

**Comment by unixorn** [comment]
@sunaku - Sorry, I managed to miss your previous comment. The other frameworks don't have code specific to this plugin, it is that their generic plugin handling code assumes they'll find `something.plugin.zsh` in a repo checkout since that is the standard used in oh-my-zsh.

**Comment by sunaku** [comment]
Per @desyncr's answer in  https://github.com/zsh-users/zsh-history-substring-search/issues/59#issuecomment-254030408, this extra `*.plugin.zsh` file is unnecessary; closing. :sweat_smile:

**Comment by Tarrasch** [comment]
@sunaku, `*.plugin.zsh` is a *convention*. Antigen is one out of many plugin managers and it's deliberately not strict on enforcing conventions. Many other plugin managers exist and even [antigen docs](https://github.com/zsh-users/antigen#notes-on-writing-plugins) suggests you to put the `*.plugin.zsh` file there.

All this said. I have strong opinions about this and in fact I have even made my own fairly popular plugin manager. :)

**Comment by sunaku** [comment]
I'm against providing a conventional `*.plugin.zsh` configuration file for this plugin because that would make the out-of-the-box experience different _only_ for users of ZSH plugin managers. :umbrella:  It would also require that we support two kinds of users: those who use ZSH plugin managers and those who do not. :two_hearts: 

Instead, I want users to look through the README and then define the keybindings and configure the documented variables to suit their own personal needs. :book: It's a one-time thing: _Just set it and forget it!_ :wind_chime:

**Comment by Tarrasch** [comment]
I'm not sure what you mean with different out-of-the-box experiences. See my post [above](https://github.com/zsh-users/zsh-history-substring-search/issues/48#issuecomment-243086044). That you both use a plugin manager *and* read the README/do configuring is nothing unique to this plugin.

**Comment by sunaku** [comment]
Restoring `*.plugin.zsh` from 2f8a5f8fe33d2f6165ac23336ed074296d65dec9, as requested by @unixorn  in this issue's description above, would provide a different out-of-the-box experience for users of ZSH plugin managers versus other users.

However, I now understand that you're asking for something else: you want to provide a `*.plugin.zsh` symlink.  Regarding this, @desyncr has answered in https://github.com/zsh-users/zsh-history-substring-search/issues/59#issuecomment-254030408 that Antigen doesn't necessarily need a `*.plugin.zsh` file because it eagerly loads _any_ `*.zsh` files.  :cake:  Therefore, providing a `*.plugin.zsh` symlink is unnecessary for Antigen (because they get the same experience whether that symlink present or absent), which is what I communicated in https://github.com/zsh-users/zsh-history-substring-search/issues/48#issuecomment-254895121 when I closed this issue. :policeman:

**Comment by Tarrasch** [comment]
Well, at least I feel confident that you understand what I mean now. I personally would stick to follow conventions to comply to as many plugin managers as possible. But I suppose you don't want the extra clutter of a symlink and stuff. Thanks for talking this through! :)
