### ISSUE TITLE
Is it possible to only search for successful commands ??

### ISSUE THREAD

**Issue by ooJerryLeeoo** [zsh-users/zsh-history-substring-search#83]
As the title

**Comment by sunaku** [comment]
Sorry for the delay. :sweat: I don't think your request is possible to implement _as-is_ because ZSH doesn't store the exit status of commands.  However, there are ZSH plugins like [zsh-histdb](https://github.com/larkery/zsh-histdb) that might make this possible.

Nevertheless, your requested feature might not be of much practical use since it's common for commands that were previously successful to fail later on (and vice versa).  For example, running `ls usr` after `cd /` would be successful, but running _that same_ `ls usr` command after `cd /tmp` might fail if `/tmp/usr` does not exist.  Consequently, it's unclear what should happen when a previously successful command from history is re-run and it now happens to fail: would you update the history, recording a failure status for the command?  (If so, your requested feature would then prevent you from fetching that command again!) :sweat_smile:
