### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by a59** [zsh-users/zsh-history-substring-search#92]
I installed this per the instructions, but it doesn't seem to do anything. 

I type say xyz then the "up arrow", and I get the previous entry from the history. 

ETA. 

bindkey "$terminfo[kcuu1]" history-substring-search-up does work.
bindkey '^[[A' history-substring-search-up does not

**Comment by aeksco** [comment]
Seeing the same problem on my end - running ZSH on `Linux Mint 18.3 Sylvia` inside TMUX.

The following key bindings work on my system:

```
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
```

[Terminfo Reference](http://pubs.opengroup.org/onlinepubs/7908799/xcurses/terminfo.html)

My suspicion is that TMUX could be causing some problems, but I'll likely not pursue the problem any further since I got it working on my end with the above `bindkey` statements.

Good luck!

**Comment by iandol** [comment]
Hi, I can confirm that "$terminfo[kcuu1]" works under Ubuntu 18.04 whereas '^[[A' etc. fails even though that is what `cat -v` shows is the key to bind...

**Comment by iandol** [comment]
Actually, I was wrong about `"$terminfo[kcuu1]"` working on macOS; it doesn't. And so if you want a cross-platform solution you need to specify different values for bindkey... 😭

**Comment by sunaku** [comment]
Exactly! :neckbeard:  We have tried using _only_ terminfo in the past, but soon learned (through user issues) that _there is no generic configuration_ that works for all platforms for binding arrow keys in ZSH. :weary: So instead, we have next best thing: an inexact how-to guide in the README. :stuck_out_tongue_winking_eye:  I have added your suggestions to the README.
